modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lighttweak"
version = "${version}"
displayName = "LightTweak"
authors = "Kall"
description = '''
'''
#logoFile = ""

[[dependencies.lighttweak]]
modId="duplicationless"
mandatory=true
versionRange="[1.1.5,)"
ordering="NONE"
side="BOTH"