modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itisme"
version = "${version}"
displayName = "ItIsMe"
authors = "Kall"
description = '''
A Minecraft mod
'''
logoFile = "logo.png"

[[dependencies.itisme]]
modId="duplicationless"
mandatory=true
versionRange="[1.1.5,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "itisme.mixins.json"
